### ISSUE TITLE
OTP expired / invalid give 422 instead of 400

### ISSUE THREAD

**Issue by amalajith** [premshyam/Node_Rest_API#10]
422 is generic for any validation failed. Now the API is giving 400, which is a status for malformed request. Here the request is fine, except that its an invalid otp, just like an invalid password or email.
<img width="1280" alt="Screenshot 2020-05-03 at 6 40 20 PM" src="https://user-images.githubusercontent.com/8926037/80915113-980a8780-8d6d-11ea-904c-e0090e1313d6.png">

**Comment by premshyam** [comment]
completed
